'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JournalVoucher

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''lbNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbNew As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSave As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbPrint control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbPrint As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbClose As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrpUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrpUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtJVNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtJVNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbReLoadJV control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbReLoadJV As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''CheckBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''cboJVtype control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboJVtype As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lbJVtype control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbJVtype As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssErrMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssErrMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRefNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRefNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnReproc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReproc As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''cboJVsource control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboJVsource As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''dpTransDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cbCentry control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cbCentry As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''cboPC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboPC As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtYear As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDfrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDfrom As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''txtRemarks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMon control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMon As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDto control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDto As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''RadioButton1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadioButton1 As Global.System.Web.UI.WebControls.RadioButton

	'''<summary>
	'''RadioButton2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadioButton2 As Global.System.Web.UI.WebControls.RadioButton

	'''<summary>
	'''txtRecJVno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRecJVno As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbRecJVno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbRecJVno As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''TabContainer1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

	'''<summary>
	'''TabPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''lbCCenter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbCCenter As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''CheckBox5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox5 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lbGLdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbGLdesc As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblSubAcct control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubAcct As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtItm As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboCCtr control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboCCtr As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboGLdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboGLdesc As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtDRamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDRamt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCRamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCRamt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblPK control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPK As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtSubAcct control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSubAcct As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Panel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvJVdet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvJVdet As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnReset control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReset As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnDel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblDRtot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDRtot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCRtot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCRtot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBalAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBalAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLineItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLineItm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssOthMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssOthMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLastDocNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLastDocNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFirstDayYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFirstDayYear As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtLastDayYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLastDayYear As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''dpDate1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpDate1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''dpDate2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpDate2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboStat As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''LbStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LbStat As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvJVsumList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvJVsumList As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''TabPanel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''txtSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSearch As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvVendor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvVendor As Global.System.Web.UI.WebControls.GridView
End Class
