'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JVPosting

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''lbNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbNew As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSave As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbPrint control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbPrint As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbClose As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrpUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrpUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtJVNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtJVNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboStat As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''dpPostDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpPostDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblJVtype2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblJVtype2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblJVtype control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblJVtype As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDateFr control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDateFr As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDateTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDateTo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lblRem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblRem As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dpFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpFrom As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''tssErrorMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssErrorMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dpTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblPrepBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPrepBy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDatePrep control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDatePrep As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cboStatList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboStatList As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lbStatList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStatList As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvJVhdr control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvJVhdr As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Panel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvJVdet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvJVdet As Global.System.Web.UI.WebControls.GridView
End Class
