'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Liquidation

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''lbNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbNew As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSave As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbPrint control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbPrint As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbClose As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrpUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrpUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblFormName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFormName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabContainer1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

	'''<summary>
	'''TabPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''dpTransDate1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''dpTransDate2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboStat As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lbStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStat As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''dgvSum control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgvSum As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Panel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''dgvGLentry control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgvGLentry As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''lblDRamtTot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDRamtTot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCRamtTot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCRamtTot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''txtJVNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtJVNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtREfNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtREfNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtVendor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtVendor As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''dpPostDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpPostDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtVPamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtVPamt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRemarks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lbCCenter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbCCenter As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbGLdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbGLdesc As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblSubAcct control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubAcct As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Panel5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblPopUpLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPopUpLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtAmtSelect control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAmtSelect As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Panel6 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel6 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''dgvMMRRlist control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgvMMRRlist As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''txtItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtItm As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboCCtr control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboCCtr As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboGLdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboGLdesc As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtDRamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDRamt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCRamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCRamt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblPK control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPK As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtSubAcct control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSubAcct As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Panel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvJVdet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvJVdet As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnReset control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReset As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnDel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblDRtot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDRtot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCRtot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCRtot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBalAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBalAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLineItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLineItm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocNoEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocNoEdit As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssNameMe control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssNameMe As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tsErrMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tsErrMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''dpTransDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboVenName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboVenName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''LinkButton1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''dgvSubs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgvSubs As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''lblDRamtTot3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDRamtTot3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDCRamtTot3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDCRamtTot3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel4 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''TabPanel5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel5 As Global.AjaxControlToolkit.TabPanel
End Class
