'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SalesOrder

	'''<summary>
	'''lbNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbNew As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSave As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbPrint control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbPrint As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbClose As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrpUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrpUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dpTransDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbReLoadSO control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbReLoadSO As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''txtSOno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSOno As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboSmnName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboSmnName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''CheckBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lblSOStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSOStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblErrMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dpDelDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpDelDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtPONo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPONo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboPlnt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboPlnt As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboPClass control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboPClass As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboCustName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboCustName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSearch As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblArea control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblArea As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTerm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTerm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCustType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCustType As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cboShipTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboShipTo As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblSPtype control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSPtype As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCRLimit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCRLimit As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblPDC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPDC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDepAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDepAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblAcctBal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAcctBal As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRemarks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lbl30days control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl30days As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbl60days control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl60days As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbl90days control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl90days As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbl91over control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl91over As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbl121over control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl121over As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbl150days control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbl150days As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''TabContainer1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

	'''<summary>
	'''TabPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''Button2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Button1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lblQtPk control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblQtPk As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''CheckBox2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''CheckBox3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''txtDiscRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDiscRate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblBillRef control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBillRef As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtItm As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCodeNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCodeNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboMMdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboMMdesc As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQty As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtWt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtSP control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSP As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDiscAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDiscAmt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblNetAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblNetAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Panel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvSOdet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvSOdet As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnReset control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReset As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnDel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblTotQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotQty As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotWt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotWt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotDiscAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotDiscAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotNetAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotNetAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLineItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLineItm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''TabPanel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel
End Class
