'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SalesInvoice

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''lbNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbNew As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSave As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbPrint control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbPrint As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbClose As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrpUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrpUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dpTransDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpTransDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtInvNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtInvNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblDSRNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDSRNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBAto control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBAto As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBranchTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBranchTo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblGrossAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrossAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDONo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDONo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboSmnName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboSmnName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblArea control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblArea As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTerm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTerm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lblTaxes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTaxes As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cboCustName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboCustName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboPC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboPC As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblCustType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCustType As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFHamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFHamt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cboShipTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboShipTo As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblCustVat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCustVat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssErrorMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssErrorMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDeductn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDeductn As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRefNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRefNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtRemarks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblNetAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblNetAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabContainer1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

	'''<summary>
	'''TabPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''CheckBox4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lblQtPk control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblQtPk As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''CheckBox3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''txtDiscRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDiscRate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblVNV control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblVNV As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBillRef control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBillRef As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtItm As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCodeNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCodeNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboMMdesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboMMdesc As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQty As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtWt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWt As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtSP control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSP As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblGrossAmtDet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGrossAmtDet As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDiscDet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDiscDet As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblNetAmtDet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblNetAmtDet As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtVATamt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtVATamt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Panel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvSalesdet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvSalesdet As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnReset control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReset As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnDel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''txtApprvdBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtApprvdBy As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblTotQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotQty As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotWt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotWt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotGross control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotGross As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotDisc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotDisc As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotNetAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotNetAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotVatAmt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotVatAmt As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tsSaveStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tsSaveStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssDocStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssDocStat As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tsDocNoEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tsDocNoEdit As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''tssVoidReqNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tssVoidReqNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblSPtype control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSPtype As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLineItm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLineItm As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''CboCustList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CboCustList As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''LbCustList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LbCustList As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvDOList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvDOList As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Panel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvDOdetList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvDOdetList As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''lblTotQtyT2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotQtyT2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTotWtT2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotWtT2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TabPanel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel

	'''<summary>
	'''dpDateFrT3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpDateFrT3 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''dpDateToT3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dpDateToT3 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboSIstatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboSIstatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lbSIstatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbSIstatus As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''Panel4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DgvSIsumList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DgvSIsumList As Global.System.Web.UI.WebControls.GridView
End Class
